version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/fctepodcast-frontend"
    schedule:
      interval: "weekly"
    target-branch: "develop"

  - package-ecosystem: "npm"
    directory: "/fctepodcast-backend"
    schedule:
      interval: "weekly"
    target-branch: "develop"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
