FROM node:alpine AS builder

WORKDIR /app

COPY package*.json /app/

RUN npm install

COPY . /app/

RUN npm run build

FROM node:alpine AS production

ENV NODE_ENV=production

WORKDIR /app

RUN npm ci --only=production

COPY --from=builder /app/dist ./dist

EXPOSE 3008

CMD ["node", "dist/app.js"]