# Build stage
FROM node:alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm install  # instala dev + prod

COPY . .

RUN npm run build

# Production stage
FROM node:alpine

WORKDIR /app

# Copia só os arquivos buildados e package.json (ou só o que precisar)
COPY --from=build /app/dist ./dist
COPY package*.json ./

RUN npm install --only=production

EXPOSE 3008

CMD ["node", "dist/app.js"]
