FROM node:alpine

ENV NODE_ENV=production

WORKDIR /app

# Copia os arquivos necessários
COPY package*.json ./

# Instala apenas as dependências de produção
RUN npm install --only=production

# Copia o restante dos arquivos (inclui src, etc.)
COPY . .

# Compila a aplicação
RUN npm run build

# Expõe a porta usada pela aplicação
EXPOSE 3008

# Comando para iniciar a aplicação
CMD ["node", "dist/app.js"]
