name: Lint and Build

on:
  push:
  pull_request:

jobs:
  lint:
    name: Run Lint (Frontend + Backend)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Lint Frontend
        run: |
          cd fctepodcast-frontend
          npm install
          npm run lint

      - name: Lint Backend
        run: |
          cd fctepodcast-backend
          npm install
          npm run lint

  build:
    name: Run Build (Frontend + Backend)
    runs-on: ubuntu-latest
    needs: lint  # build só roda se o lint passar

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build Frontend
        run: |
          cd fctepodcast-frontend
          npm install
          npm run build

      - name: Build Backend
        run: |
          cd fctepodcast-backend
          npm install
          npm run build

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Call Webhook to Deploy
        run: |
          curl -X POST ${{ secrets.DEPLOY_WEBHOOK_URL }}

