name: Teste de Lint Backend e Frontend

on:
  push:
  pull_request:

jobs:
  lint-frontend:
    name: Lint Frontend
    runs-on: ubuntu-latest
    defaults:
      runs: 
        working-directory: fctepodcast-frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Run Lint
        run: npm run lint

  lint-backend:
    name: Lint Backend
    runs-on: ubuntu-latest
    defaults:
      runs:
        working-directory: fctepodcast-backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node  
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install    

      - name: Run Lint
        run: npm run lint
